name: Deploy to AWS

on:
  push:
    branches:
      - main

env:
  DOCKER_IMAGE: ghcr.io/${{ github.actor }}/personal-project-fastapi
  VERSION: ${{ github.sha }}
  NAME: personal-project-fastapi

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:   
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Configure Docker
        uses: docker/setup-buildx-action@v1

      - name: Cache Docker Layers
        uses: actions/cache@v2
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ env.VERSION }}
          restore-keys:
            ${{ runner.os }}-buildx-
      - name: Set up Docker Buildkit
        run: |
          echo "DOCKER_BUILDKIT=1" >> $GITHUB_ENV

      - name: Login to GHCR
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{secrets.GHCR_TOKEN }}

      - name: Create account for email authentication
        run: |
          pwd
          echo "${{ secrets.EMAIL_ACCOUNT }}" > app/email_info/email_info.py
          python ./app/email_info/email_info.py
          cat app/email_info/account

      - name: Create flight_api for flight search
        run: |
          pwd
          echo "${{ secrets.FLIGHT_API }}" > app/flight_api/flight_api_info.py
          python ./app/flight_api/flight_api_info.py
          cat app/flight_api/flight_api

      - name: Create env for deploy config
        run: |
          pwd
          echo "${{ secrets.CD_DEPLOY_CONFIG }}" > .env
          cat .env

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ghcr.io/zage4448/personal-project-fastapi:latest
          platforms: linux/arm64
          



  deploy:
    needs: build
    name: Deploy
    runs-on: [ self-hosted, travelers-guide-fastapi ]
    steps:
      - name: Login to ghcr
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_TOKEN }}


      - name: Deploy to prod
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.HOST_PROD }}
          username: ec2-user
          key: ${{ secrets.PRIVATE_KEY }}
          script_stop : true
          script: |
            pwd
            ls -al
            cd travelers-guide/fastapi-server
            pwd
            
            echo ${{ secrets.GHCR_TOKEN }} | docker login ghcr.io -u ${{ github.repository_owner }} --password-stdin
            
            docker pull ghcr.io/zage4448/personal-project-fastapi:latest
            
            docker image prune -f
            docker logout
            
            docker-compose up -d
